name: Run tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Run tests
        run: cargo test --verbose
